In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [2]:
       df = pd.read_csv('../data/cleaned_telco_churn.csv')

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.shape

(7043, 21)

In [5]:
df = df.drop('customerID', axis=1)

In [6]:
df.shape

(7043, 20)

In [7]:
df['Churn'] = df['Churn'].map({
    'Yes': 1,
    'No': 0
})

In [8]:
df['Churn'].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [9]:
df.nunique()

gender                 2
SeniorCitizen          2
Partner                2
Dependents             2
tenure                73
PhoneService           2
MultipleLines          3
InternetService        3
OnlineSecurity         3
OnlineBackup           3
DeviceProtection       3
TechSupport            3
StreamingTV            3
StreamingMovies        3
Contract               3
PaperlessBilling       2
PaymentMethod          4
MonthlyCharges      1585
TotalCharges        6531
Churn                  2
dtype: int64

In [10]:
df['gender'] = df['gender'].map({
    'Male': 1,
    'Female': 0
})

binary_cols = [
    'Partner',
    'Dependents',
    'PhoneService',
    'PaperlessBilling'
]

for col in binary_cols:
    df[col] = df[col].map({
        'Yes': 1,
        'No': 0
    })

In [11]:
df[['gender',
    'Partner',
    'Dependents',
    'PhoneService',
    'PaperlessBilling',
    'Churn']].head()

   gender  Partner  Dependents  PhoneService  PaperlessBilling  Churn
0       0        1           0             0                 1      0
1       1        0           0             1                 0      0
2       1        0           0             1                 1      1
3       1        0           0             0                 0      0
4       0        0           0             1                 1      1

In [12]:
categorical_cols = [
    'MultipleLines',
    'InternetService',
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies',
    'Contract',
    'PaymentMethod'
]

df = pd.get_dummies(
    df,
    columns=categorical_cols,
    drop_first=True
)

In [13]:
df.shape

(7043, 31)

In [14]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,...,TechSupport_Yes,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,1,29.85,29.85,0,...,False,False,False,False,False,False,False,False,True,False
1,1,0,0,0,34,1,0,56.95,1889.50,0,...,False,False,False,False,False,True,False,False,False,True
2,1,0,0,0,2,1,1,53.85,108.15,1,...,False,False,False,False,False,False,False,False,False,True
3,1,0,0,0,45,0,0,42.30,1840.75,0,...,True,False,False,False,False,True,False,False,False,False
4,0,0,0,0,2,1,1,70.70,151.65,1,...,False,False,False,False,False,False,False,False,True,False

In [15]:
X = df.drop('Churn', axis=1)

y = df['Churn']

In [16]:
df.shape

(7043, 31)

In [17]:
X.shape

(7043, 30)

In [18]:
y.shape

(7043,)

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [20]:
from sklearn.linear_model import LogisticRegression

In [21]:
model = LogisticRegression(max_iter=1000)

In [22]:
model.fit(X_train, y_train)

C:\Users\hp 1040\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression(max_iter=1000)

In [23]:
y_pred = model.predict(X_test)

In [24]:
from sklearn.metrics import accuracy_score

In [25]:
accuracy_score(y_test, y_pred)

0.8048261178140526

In [26]:
from sklearn.metrics import confusion_matrix

In [27]:
confusion_matrix(y_test, y_pred)

array([[924, 111],
       [164, 210]])

In [28]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1035
           1       0.65      0.56      0.60       374

    accuracy                           0.80      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.80      0.80      1409

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
rf = RandomForestClassifier(
    random_state=42
)

In [31]:
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [32]:
rf_pred = rf.predict(X_test)

In [33]:
accuracy_score(y_test, rf_pred)

0.78708303761533

In [34]:
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1035
           1       0.63      0.49      0.55       374

    accuracy                           0.79      1409
   macro avg       0.73      0.69      0.71      1409
weighted avg       0.78      0.79      0.78      1409

In [35]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, rf_pred)

array([[926, 109],
       [191, 183]])

In [36]:
coef_df = pd.DataFrame({
    'Feature': X.columns,
    'Coefficient': model.coef_[0]
})

In [37]:
coef_df.sort_values(
    by='Coefficient',
    ascending=False
).head(10)

                           Feature  Coefficient
11     InternetService_Fiber optic     0.764561
28  PaymentMethod_Electronic check     0.387446
6                 PaperlessBilling     0.377625
10               MultipleLines_Yes     0.279504
24             StreamingMovies_Yes     0.219640
22                 StreamingTV_Yes     0.217265
9   MultipleLines_No phone service     0.169783
1                    SeniorCitizen     0.145127
29      PaymentMethod_Mailed check     0.081703
2                          Partner     0.028870

In [38]:
coef_df.sort_values(
    by='Coefficient'
).head(10)

                                 Feature  Coefficient
26                     Contract_Two year    -1.332473
25                     Contract_One year    -0.690857
14                    OnlineSecurity_Yes    -0.433320
5                           PhoneService    -0.408719
20                       TechSupport_Yes    -0.384167
3                             Dependents    -0.219688
16                      OnlineBackup_Yes    -0.179490
15      OnlineBackup_No internet service    -0.115607
17  DeviceProtection_No internet service    -0.115607
19       TechSupport_No internet service    -0.115607

In [39]:
import joblib

joblib.dump(
    model,
    '../models/logistic_regression.pkl'
)

['../models/logistic_regression.pkl']

## Conclusion

The customer churn prediction model was developed using the Telco Customer Churn dataset. After preprocessing and feature engineering, Logistic Regression and Random Forest models were trained and evaluated.

Logistic Regression achieved an accuracy of 80% and outperformed Random Forest in terms of recall and F1-score for churn prediction.

Feature importance analysis revealed that Fiber Optic Internet, Electronic Check payment method, and Paperless Billing were associated with higher churn risk. In contrast, customers with One-Year and Two-Year contracts, Online Security, and Tech Support services were significantly less likely to churn.

Based on these findings, the company should focus on encouraging long-term contracts, improving retention strategies for Fiber Optic users, and promoting value-added services such as Online Security and Tech Support.